### ISSUE TITLE
How do I open it in my Xcode?

### ISSUE THREAD

**Issue by diegodp-zz** [Atrolide/WorkoutPal#1]
Hello my friend, I am studying Swift and I want to see your app in Xcode, I am new in this and I am self learning swift, can you help me how do I open your project correctly in my Xcode?  Thank you

**Comment by Atrolide** [comment]
First you will need to clone the repository. To do this go to terminal and navigate to the folder where you want to have the project.
Then input the following command:
```txt
git clone https://github.com/Atrolide/WorkoutPal.git
```
**(I assume that you have git installed on you computer)**

Then open XCode, Click Open on the Welcome screen or File | Open from the main menu. Navigate to the desired . xcodeproj directory.

If you still have trouble opening the project message me again, I will try to help :)
